### PR TITLE
Add testing and build support for Fedora

### PR DESCRIPTION
**Pull request by tzz**
This PR adds the ability to use multiple platforms, with Fedora as the first addition.

This PR is not 100% functional because Fedora needs `supervisord` or something similar inside Docker to run SSH. But I think we should disable SSH in any case and only allow access with `docker exec` which is faster and more secure. So don't merge yet.

The bigger question is that, since Debian uses systemd inside Docker and Fedora doesn't, this is a fundamentally different setup from the original that @bahamat wrote. So, do we use something like https://developerblog.redhat.com/2014/05/05/running-systemd-within-docker-container/ and https://dingyichen.wordpress.com/2014/11/25/running-systemd-within-a-docker-container-with-rhel7/ to work around things? Or do we accept the Docker way of running a single service and focus on just running `cf-serverd`?

For the purposes of running a CFEngine policy hub, the Docker way is cleaner. For the purposes of testing policy, the systemd way is more appropriate. So this may be a point where the testing side of this repo has to diverge into a separate repo (while perhaps retaining common files and logic).

Let me know what you think @bahamat @garywall @nickanderson

### CODE REVIEW

**Comment by tzz** [comment]
I plan to add CentOS and RHEL 7 after Fedora, then maybe others.

**Comment by bahamat** [comment]
I believe that renaming the Dockerfile will break automate builds in docker hub, which is something I don't want to happen.

**Comment by bahamat** [comment]
Docker hub supports alternate builds using branches, so maybe we should split all of these to each have their own branch. But I'm not really sure what the right answer is yet.

**Comment by tzz** [comment]
Docker hub definitely supports multiple builds from the same branch and alternative Dockerfiles, I just checked and enabled it in https://hub.docker.com/r/tzlatanov/docker-cfengine-policy-hub against my `master` branch. I just don't know if the Dockerfile location needs to be a directory or just a filename, and I can rearrange as needed to accomodate our Dockerlords.

Assuming that's OK, what about the general question about systemd and testing vs. pure hub?

**Comment by tzz** [comment]
@bahamat I added you as collaborator to https://hub.docker.com/r/tzlatanov/docker-cfengine-policy-hub/ so you can play with it too.

**Comment by tzz** [comment]
Yeah I can confirm multiple Dockerfiles work fine.

**Comment by tzz** [comment]
ping?

**Comment by bahamat** [comment]
You had said it wasn't 100% functional, so I was waiting for that to be fixed.

**Comment by tzz** [comment]
Well, I'm not sure if I should disable SSH or try to bring up a full Debian/Fedora system. That's what I meant about the direction: should this be a fully functional hub and nothing more, or should it be a full testbed? Or can it be both? The fixes depend on your ideas about where this is going to go :)

**Comment by bahamat** [comment]
Oh, I see.

My purpose was never to emulate full systems. It was just to have a functioning hub.

Trying to emulate a full system, in my opinion, is antithetical to the usage pattern of Docker. It has been engineered, whether by intent or accident, to make these sorts of things difficult to nearly impossible. Though there have been some efforts outside of Docker to try to correct that (e.g., [ContainerBuddy](http://www.containerbuddy.com/). I would be more inclined to go with something like ContainerBuddy than to try to emulate a full distro.

**Comment by tzz** [comment]
All right, so I've set up https://github.com/tzz/cfengine-docker-testbed  linked to https://hub.docker.com/r/tzlatanov/cfengine-docker-testbed/ for the testbed I needed. You can close this PR and pull out all my testing-related changes if you want.

**Pull request closed without merging**
